### ISSUE TITLE
Falha nos testes

### ISSUE THREAD

**Issue by guimaraaes** [devfullcycle/fc-monolito#6]
Estou com problema para executar o projeto do repositório da full cycle, quando baixo e rodos os testes tenho 12 testes falhando sem ter realizado nenhuma alteração no código

**Comment by LucianTavares** [comment]
Olá Sara, tudo bem com você?

Testei o nosso código aqui e tudo esta funcionando corretamente.
Me chame no Discord: luciantavares ou no e-mail: lucian@fullcycle.com.br

Obrigado.

**Comment by emiliosheinz** [comment]
@guimaraaes Da uma olhada nesse repo https://github.com/emiliosheinz/full-cycle-monolithic-systems. Também tive problemas ao rodar os tests e corrigi eles lá. Se não me engano ele não reconhecia as annotations.
